id: I9C38BC4C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T23:16:21+00:00'
last_modified: '2022-06-07T17:14:01.840130+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD90704
  title: ས་སྐྱའི་ཆོས་འབྱུང་གཅེས་བསྡུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '5086':
      image_group_id: I1PD90706
      title: ''
      total_pages: 186
      order: 1
      base_file: 5086.txt
    A7F1:
      image_group_id: I1PD90707
      title: ''
      total_pages: 249
      order: 2
      base_file: A7F1.txt
    D3F6:
      image_group_id: I1PD90708
      title: ''
      total_pages: 238
      order: 3
      base_file: D3F6.txt
    1B6D:
      image_group_id: I1PD90709
      title: ''
      total_pages: 240
      order: 4
      base_file: 1B6D.txt
    9B95:
      image_group_id: I1PD90710
      title: ''
      total_pages: 248
      order: 5
      base_file: 9B95.txt
    7E30:
      image_group_id: I1PD90711
      title: ''
      total_pages: 634
      order: 6
      base_file: 7E30.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
